server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/urlshortener
spring.datasource.username=vyshnavikommu
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update

spring.data.redis.host=localhost
spring.data.redis.port=6379